// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZTQGmeGmFroTq1TESOVaw1vcYITT_rLE',
    appId: '1:704826181820:web:147f8056027671ad14e8b9',
    messagingSenderId: '704826181820',
    projectId: 'imdaat-talimiyah',
    authDomain: 'imdaat-talimiyah.firebaseapp.com',
    storageBucket: 'imdaat-talimiyah.firebasestorage.app',
    measurementId: 'G-ZQC2EP2JL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH4zdv-iuI5gBLVBB1denEZUu4PfI_b6w',
    appId: '1:704826181820:android:131df73809ec33c714e8b9',
    messagingSenderId: '704826181820',
    projectId: 'imdaat-talimiyah',
    storageBucket: 'imdaat-talimiyah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPl4ETd2ZtuT2XVYY-ATLUlQhrMywTfAk',
    appId: '1:704826181820:ios:de639610c8732d4814e8b9',
    messagingSenderId: '704826181820',
    projectId: 'imdaat-talimiyah',
    storageBucket: 'imdaat-talimiyah.firebasestorage.app',
    iosBundleId: 'com.example.imdaatTaleemiyahRecipt',
  );
}
